### ISSUE TITLE
Required login after each start

### ISSUE THREAD

**Issue by thekarinka** [SylvainCecchetto/recipe-riot#1]
Hello, every time when I start (or quit and start again Franz) I must login into Riot because it doesn't remember my session. When person is using encrypting it is required to verify "new" device on other devices every time. Does somebody else have this problem?

**Comment by sy6sy2** [comment]
Hello,

I have this problem too, it's my first riot recipe so maybe I missed something. I will check on other recipes like Messenger to see I there is an option or something like that to keep the account login between a restart of Franz. Maybe cookies ?

**Comment by thekarinka** [comment]
Hello,

yes, it could be cookies. Or I had got idea that it could be caused by running it in dev mode...

**Comment by thekarinka** [comment]
So, riot has been deployed to official repository and it isn't caused by running in dev mode. But I has been discussing it with my friend and maybe it could be caused by localStorage. Btw. when you open application in browser and check local storage, you can found here a lot of properties. When you check storage in Franz, there isn`t any from properties showed in browser. Maybe webview is using own localstorage seperated from "main Franz local storage"...

**Comment by sy6sy2** [comment]
Oh, maybe it's that .. I asked about that on Franz slack channel and the Franz dev knows the issue and he says that this issue happen with others web services but he don't know why.
Maybe you are right and it could be useful if you share this information with him on Slack?
In my case I'm not a "web" expert. I just create this plugin because I needed it =D
But if this issue can be resolved it could be very nice!

**Comment by thekarinka** [comment]
Thanks, we found that it can be fixed by updating : `"serviceURL": "https://riot.im/app/#/login",` to `"serviceURL": "https://riot.im/app",` 
I tested it and it is working :).

**Comment by sy6sy2** [comment]
Hey! Cool if it works! I will test myself and if it works I will make a PR to official Riot recipe to update the plugin.
Do you know why it works with this URL?

Edit: Nice! It works :D (https://github.com/meetfranz/plugins/issues/75)

**Comment by thekarinka** [comment]
No, I don`t why... But Stefan recommend it me and it`s working :). Maybe it`s becuase when you visit explicitly login page, you will receive new encrypt keys, while you are visiting own app, you`re explicitly searching for keys. So, I think, that is rare combination a lot of aspects which need special solution :).
I`m closing this issue, it`s already done. Thank for cooperation! :)
